# Generated by Django 2.2.7 on 2019-11-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='price_sum',
            field=models.IntegerField(blank=True),
        ),
    ]
