# Generated by Django 2.2.7 on 2019-11-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191125_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='price_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
